In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\ritam.borah\Downloads\CampusX\Day 28\covid_toy.csv")

In [3]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
df.shape

(100, 6)

In [6]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [7]:
df.head(1)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No

In [10]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [11]:
# 10 values are missing from the fever colum

In [12]:
df['fever'].isnull().sum()

10

In [17]:
df.head(1)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No

#### Here in the gender column we have to apply OneHotEncoding 
#### Here in the cough column we have to apply OrdinalEncoder 
#### Here in the city column we have to apply OneHotEncoding 
#### Here in the has_covid column we have to apply LabelEncoder but this is not the main priority today 

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.drop('has_covid', axis=1), df['has_covid'], test_size=0.2, random_state=2)

In [19]:
X_train.shape, X_test.shape

((80, 5), (20, 5))

In [21]:
X_train.head()

age  gender  fever   cough       city
35   82  Female  102.0  Strong  Bangalore
11   65  Female   98.0    Mild     Mumbai
84   69  Female   98.0  Strong     Mumbai
44   20    Male  102.0  Strong      Delhi
73   34    Male   98.0  Strong    Kolkata

# Aam jindegi

In [23]:
# adding simple inputer to the fever column
si = SimpleImputer()

X_train_fever = si.fit_transform(X_train[['fever']])
X_test_fever = si.fit_transform(X_test[['fever']])

In [25]:
print(X_train_fever)

[[102.        ]
 [ 98.        ]
 [ 98.        ]
 [102.        ]
 [ 98.        ]
 [100.79166667]
 [100.79166667]
 [101.        ]
 [104.        ]
 [104.        ]
 [102.        ]
 [100.        ]
 [ 98.        ]
 [ 99.        ]
 [101.        ]
 [100.        ]
 [101.        ]
 [103.        ]
 [100.79166667]
 [100.79166667]
 [ 99.        ]
 [ 98.        ]
 [101.        ]
 [ 99.        ]
 [104.        ]
 [101.        ]
 [100.79166667]
 [100.        ]
 [102.        ]
 [101.        ]
 [101.        ]
 [101.        ]
 [ 98.        ]
 [104.        ]
 [ 99.        ]
 [100.79166667]
 [104.        ]
 [ 99.        ]
 [101.        ]
 [100.        ]
 [104.        ]
 [100.79166667]
 [ 99.        ]
 [ 98.        ]
 [104.        ]
 [ 99.        ]
 [101.        ]
 [100.        ]
 [104.        ]
 [100.        ]
 [101.        ]
 [101.        ]
 [104.        ]
 [103.        ]
 [ 99.        ]
 [ 98.        ]
 [ 98.        ]
 [101.        ]
 [100.        ]
 [100.        ]
 [101.        ]
 [ 99.        ]
 [103.  

In [26]:
X_train_fever.shape

(80, 1)

In [33]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])

X_train_cough = oe.fit_transform(X_train[['cough']])
X_test_cough = oe.fit_transform(X_test[['cough']])

In [34]:
X_train_cough.shape

(80, 1)

In [35]:
X_train['gender'].value_counts()

gender
Female    48
Male      32
Name: count, dtype: int64

In [36]:
X_train['city'].value_counts()

city
Bangalore    26
Kolkata      22
Delhi        18
Mumbai       14
Name: count, dtype: int64

In [37]:
# OneHotEncoding -> gender, city
oe = OneHotEncoder(drop='first', sparse_output=False)

X_train_gender_city = oe.fit_transform(X_train[['gender', 'city']])
X_test_gender_city = oe.fit_transform(X_test[['gender', 'city']])

In [38]:
X_test_gender_city

array([[0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]])

In [39]:
X_train.head(1)

age  gender  fever   cough       city
35   82  Female  102.0  Strong  Bangalore

In [43]:
X_train_age = X_train.drop(columns=['gender', 'fever', 'cough', 'city'], axis=1).values
X_test_age = X_test.drop(columns=['gender', 'fever', 'cough', 'city'], axis=1).values

In [45]:
X_train_age

array([[82],
       [65],
       [69],
       [20],
       [34],
       [84],
       [23],
       [ 8],
       [34],
       [56],
       [69],
       [27],
       [64],
       [66],
       [38],
       [11],
       [14],
       [46],
       [38],
       [75],
       [25],
       [83],
       [47],
       [60],
       [12],
       [34],
       [42],
       [19],
       [24],
       [81],
       [64],
       [51],
       [40],
       [ 6],
       [49],
       [82],
       [42],
       [72],
       [20],
       [19],
       [75],
       [79],
       [59],
       [ 5],
       [25],
       [14],
       [19],
       [47],
       [51],
       [ 5],
       [68],
       [19],
       [54],
       [73],
       [65],
       [23],
       [26],
       [49],
       [11],
       [27],
       [65],
       [65],
       [50],
       [55],
       [12],
       [83],
       [10],
       [18],
       [16],
       [27],
       [44],
       [74],
       [20],
       [ 5],
       [24],
       [22],
       [71],

In [46]:
X_train_age.shape

(80, 1)

In [47]:
X_train_transformed = np.concatenate((X_train_age, X_train_fever, X_train_gender_city, X_train_cough), axis=1)
X_test_transformed = np.concatenate((X_test_age, X_test_fever, X_test_gender_city, X_test_cough), axis=1)

In [48]:
X_train_transformed.shape

(80, 7)

In [49]:
X_train_transformed

array([[ 82.        , 102.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 65.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 69.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 20.        , 102.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 34.        ,  98.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 84.        , 100.79166667,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 23.        , 100.79166667,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [  8.        , 101.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 34.        , 104.        ,   0.        ,   1.        ,
          0.    

# Mentos Zindegi

In [50]:
from sklearn.compose import ColumnTransformer

In [51]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(), ['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
    ('tnf3', OneHotEncoder(drop='first', sparse_output=False), ['gender', 'city'])
], remainder='passthrough')

In [53]:
transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('tnf1', SimpleImputer(), ['fever']),
                                ('tnf2',
                                 OrdinalEncoder(categories=[['Mild',
                                                             'Strong']]),
                                 ['cough']),
                                ('tnf3',
                                 OneHotEncoder(drop='first',
                                               sparse_output=False),
                                 ['gender', 'city'])])

In [54]:
transformer.fit_transform(X_train)

array([[102.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  82.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  65.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  69.        ],
       [102.        ,   1.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  20.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  34.        ],
       [100.79166667,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  84.        ],
       [100.79166667,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  23.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   8.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.    